name: Release

on:
  workflow_dispatch: # Allow manual trigger
  push:
    tags:
      - 'v*' # Trigger workflow when a tag like v1.0.0 is pushed

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false # Don't cancel Windows if Mac fails
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 # Use a more stable LTS version
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build and Release Electron App
        run: |
          npx electron-vite build
          npx electron-builder --publish always
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
